0-give_me_a_page

diff --git a/0x0D-web_stack_debugging_0/0-give_me_a_page b/0x0D-web_stack_debugging_0/0-give_me_a_page
--- a/0x0D-web_stack_debugging_0/0-give_me_a_page
+++ b/0x0D-web_stack_debugging_0/0-give_me_a_page
@@ -1,13 +1,15 @@
 
-#!/usr/bin/env bash
-# Start Apache so as to return a
-service apache2 start
-
-# Set up Apache server
-# IP="$(curl ifconfig.me)"
+# Start Apache
+systemctl start apache2
 
 # Set ServerName to IP
-# sudo sed -i "s/#ServerName www.example.com/ServerName $IP/" /etc/apache2/sites-available/000-default.conf
+# IP="$(curl ifconfig.me)"
+# sed -i "s/#ServerName www.example.com/ServerName $IP/" /etc/apache2/sites-available/000-default.conf
 
-# Start Apache
-sudo service apache2 start
+# Check if Apache started successfully
+if systemctl is-active --quiet apache2; then
+    echo "Apache started successfully."
+else
+    echo "Failed to start Apache."
+    exit 1
+fi
