0-give

diff --git a/0x0D-web_stack_debugging_0/0-give_me_a_page b/0x0D-web_stack_debugging_0/0-give_me_a_page
--- a/0x0D-web_stack_debugging_0/0-give_me_a_page
+++ b/0x0D-web_stack_debugging_0/0-give_me_a_page
@@ -1,13 +1,20 @@
-
 #!/usr/bin/env bash
-# Start Apache so as to return a
-service apache2 start
+# Script to start Apache and configure ServerName
 
-# Set up Apache server
-# IP="$(curl ifconfig.me)"
+# Check if running with root privileges
+if [ "$(id -u)" -ne 0 ]; then
+    echo "This script must be run with sudo or as root" 1>&2
+    exit 1
+fi
 
-# Set ServerName to IP
-# sudo sed -i "s/#ServerName www.example.com/ServerName $IP/" /etc/apache2/sites-available/000-default.conf
-
-# Start Apache
+# Start Apache service
 sudo service apache2 start
+
+# Set ServerName to IP address
+# IP="$(curl -s ifconfig.me)"
+# if [ -n "$IP" ]; then
+#     sudo sed -i "s/#ServerName www.example.com/ServerName $IP/" /etc/apache2/sites-available/000-default.conf
+# else
+#     echo "Failed to retrieve IP address" 1>&2
+#     exit 1
+# fi
